conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from ikwen_webnode.webnode.views import FlatPageView

from council.views import Home
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'conf.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^$', Home.as_view(), name='home'),
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^pinsview/', include('pinsview.urls', namespace='pinsview')),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),
    url(r'^', include('council.urls', namespace='council')),
    url(r'^$', Home.as_view(), name='home')
)

council/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required, permission_required

from council.views import Home, PaymentOrderList, Dashboard, ChangeTax, TaxList, Receipt, ChangePaymentOrder, \
    EditProfile, ProfileList, set_momo_payment, confirm_payment, PaymentList, Maps, \
    notify_outdated_payment_orders, ChangeProfile, ChangeBanner, BannerList, ProjectList, ChangeProject, CategoryList, ChangeCategory

urlpatterns = patterns(
    '',

    url(r'^kmth/dashboard/$', permission_required('council.ik_manage_dashboard')(Dashboard.as_view()),
                                                                                name='dashboard'),


    url(r'^kmth/payments/$', permission_required('council.ik_manage_payment')(PaymentList.as_view()), name='payment_list'),


    url(r'^kmth/categoryList/$', permission_required('council.ik_manage_category')(CategoryList.as_view()), name='category_list'),
    url(r'^kmth/changeCategory/$', permission_required('council.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),
    url(r'^kmth/changeCategory/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_category')(ChangeCategory.as_view()),
        name='change_category'),

    url(r'^kmth/taxList/$', permission_required('council.ik_manage_tax')(TaxList.as_view()), name='tax_list'),
    url(r'^kmth/changeTax/$', permission_required('council.ik_manage_tax')(ChangeTax.as_view()), name='change_tax'),
    url(r'^kmth/changeTax/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeTax.as_view()),
        name='change_tax'),


    url(r'^kmth/changeProfile/$', permission_required('council.ik_view_profile')(ChangeProfile.as_view()), name='change_profile'),
    url(r'^kmth/changeProfile/(?P<object_id>[-\w]+)/$',
        permission_required('council.ik_view_profile')(ChangeProfile.as_view()), name='change_profile'),
    url(r'^kmth/profileList/$', permission_required('council.ik_view_profile')(ProfileList.as_view()), name='profile_list'),


    url(r'^kmth/changeProject/$', permission_required('council.ik_view_project')(ChangeProject.as_view()),
        name='change_project'),
    url(r'^kmth/changeProject/(?P<object_id>[-\w]+)/$',
        permission_required('council.ik_view_profile')(ChangeProject.as_view()), name='change_project'),
    url(r'^kmth/projectList/$', permission_required('council.ik_view_project')(ProjectList.as_view()),
        name='project_list'),

    url(r'^kmth/paymentOrderList$',
        permission_required('council.ik_manage_payment_order')(PaymentOrderList.as_view()),
        name='paymentorder_list'),
    url(r'^kmth/changePaymentOrder/$',
        permission_required('council.ik_manage_payment_order')(ChangePaymentOrder.as_view()),
        name='change_paymentorder'),
    url(r'^kmth/changePaymentOrder/(?P<object_id>[-\w]+)$',
        permission_required('council.ik_manage_payment_order')(ChangePaymentOrder.as_view()), name='change_paymentorder'),


    url(r'^kmth/BannerList/$', permission_required('council.ik_manage_tax')(BannerList.as_view()), name='banner_list'),
    url(r'^kmth/changeBanner/$', permission_required('council.ik_manage_tax')(ChangeBanner.as_view()), name='change_banner'),
    url(r'^kmth/changeBanner/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeBanner.as_view()),
        name='change_banner'),


    # url(r'^home/$', Home.as_view(), name='home'),
    url(r'^profile/edit$', login_required(EditProfile.as_view()), name='edit_profile'),
    url(r'^maps$', login_required(Maps.as_view()), name='maps'),
    url(r'^receipt/(?P<receipt_id>[-\w]+)/$', login_required(Receipt.as_view()), name='receipt'),

    url(r'^set_momo_payment$', set_momo_payment),
    url(r'^confirm_payment/(?P<tx_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_payment, name='confirm_payment'),

    url(r'^notif$', notify_outdated_payment_orders, name='notify_outdated_payment_orders'),
)

council/views.py
import logging
import random
import string
from datetime import timedelta, datetime
from threading import Thread

# Create your views here.

import requests
from django.conf import settings
from django.contrib import messages
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.utils.translation import ugettext as _
from django.views.generic import TemplateView

from ikwen.accesscontrol.models import Member
from ikwen.conf.settings import WALLETS_DB_ALIAS
from ikwen.core.constants import CONFIRMED
from ikwen.core.templatetags.url_utils import strip_base_alias
from ikwen.core.utils import increment_history_field
from ikwen.billing.models import MoMoTransaction, MTN_MOMO
from ikwen.billing.utils import get_next_invoice_number

from ikwen.core.views import HybridListView, DashboardBase, ChangeObjectBase
from ikwen.core.utils import set_counters, get_service_instance, \
    get_mail_content
from ikwen.billing.invoicing.views import Payment

from council.models import PaymentOrder, Profile, Tax, Payment, Banner, Project, Category
from council.admin import PaymentOrderAdmin, ProfileAdmin, TaxAdmin, PaymentAdmin, BannerAdmin, ProjectAdmin, CategoryAdmin
from pinsview.models import Pin, PinCategory, City, Zone

logger = logging.getLogger('ikwen')


class Dashboard(DashboardBase):
    # template_name = 'council/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        return context


class Home(HybridListView):
    model = Tax
    model_admin = TaxAdmin
    template_name = 'council/show_tax_list.html'
    html_results_template_name = 'council/snippets/tax_list_results.html'

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        config = get_service_instance().config
        created_profile = False
        if self.request.user.is_authenticated():
            if Profile.objects.filter(member=self.request.user):
                created_profile = True
        context['created_profile'] = created_profile
        context['banner'] = Banner.objects.first()
        context['currency_symbol'] = config.currency_symbol
        return context


class ChangeTax(ChangeObjectBase):
    model = Tax
    model_admin = TaxAdmin


class TaxList(HybridListView):
    model = Tax
    model_admin = TaxAdmin


class ChangeBanner(ChangeObjectBase):
    model = Banner
    model_admin = BannerAdmin


class BannerList(HybridListView):
    model = Banner
    model_admin = BannerAdmin


class PaymentOrderList(HybridListView):
    model = PaymentOrder
    model_admin = PaymentOrderAdmin


class Receipt(TemplateView):
    template_name = 'council/receipt.html'

    def get_context_data(self, **kwargs):
        context = super(Receipt, self).get_context_data(**kwargs)
        config = get_service_instance().config
        receipt_id = self.kwargs.get('receipt_id')
        try:
            payment = Payment.objects.select_related('tax', 'member').get(pk=receipt_id)
        except Payment.DoesNotExist:
            raise Http404("Payment not found")
        context['currency_symbol'] = config.currency_symbol
        context['payment'] = payment
        context['member'] = payment.member
        context['amount'] = payment.tax.cost
        context['payment_number'] = get_next_invoice_number()
        return context


class PaymentList(HybridListView):
    model = Payment
    model_admin = PaymentAdmin


class ChangePaymentOrder(ChangeObjectBase):
    model = PaymentOrder
    model_admin = PaymentOrderAdmin

    def after_save(self, request, obj, *args, **kwargs):
        member_id = request.POST['member_id']
        member = Member.objects.get(pk=member_id)
        obj.provider = member
        obj.save()


class EditProfile(ChangeObjectBase):
    template_name = 'council/edit_profile.html'
    model = Profile
    model_admin = ProfileAdmin

    def get_context_data(self, **kwargs):
        context = super(EditProfile, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        try:
            context['profile'] = Profile.objects.get(member=self.request.user)
        except:
            pass
        return context

    def get_object(self, **kwargs):
        if self.request.user.is_authenticated():
            try:
                profile = Profile.objects.get(member=self.request.user)
            except:
                profile = Profile.objects.create(member=self.request.user)
            return profile

    def after_save(self, request, obj):
        try:
            category = PinCategory.objects.get(name=obj.business_type.name)
        except:
            category = PinCategory.objects.create(name=obj.business_type.name)
        try:
            city = City.objects.get(name=obj.formatted_address.split(',')[1])
        except:
            city = City.objects.create(name=obj.formatted_address.split(',')[1])
        try:
            zone = Zone.objects.get(name=obj.formatted_address.split(',')[0], city=city)
        except:
            zone = Zone.objects.create(name=obj.formatted_address.split(',')[0], city=city)
        Pin.objects.create(category=category, name=obj.member.full_name,
                              city=city, latitude=obj.location_lat,
                              longitude=obj.location_lng, created_on=obj.created_on, updated_on=obj.updated_on)
        return HttpResponseRedirect(reverse('home') + "?profile_created=yes")


class ChangeCategory(ChangeObjectBase):
    model = Category
    model_admin = CategoryAdmin


class CategoryList(HybridListView):
    model = Category


class ProjectList(HybridListView):
    model = Project
    model_admin = ProjectAdmin


class ChangeProject(ChangeObjectBase):
    model = Project
    model_admin = ProjectAdmin


class ChangeProfile(ChangeObjectBase):
    model = Profile
    model_admin = ProfileAdmin
    template_name = 'council/change_profile.html'


class ProfileList(HybridListView):
    model = Profile


def set_momo_payment(request, *args, **kwargs):
    service = get_service_instance()
    config = service.config
    product_id = request.POST['product_id']
    product = Tax.objects.get(pk=product_id)
    payment = Payment.objects.create(member=request.user, tax=product, method=Payment.MOBILE_MONEY,
                                     amount=product.cost)
    model_name = 'council.Payment'
    mean = request.GET.get('mean', MTN_MOMO)
    signature = ''.join([random.SystemRandom().choice(string.ascii_letters + string.digits) for i in range(16)])
    MoMoTransaction.objects.using(WALLETS_DB_ALIAS).filter(object_id=product.id).delete()
    tx = MoMoTransaction.objects.using(WALLETS_DB_ALIAS)\
        .create(service_id=service.id, type=MoMoTransaction.CASH_OUT, amount=product.cost, phone='N/A', model=model_name,
                object_id=payment.id, task_id=signature, wallet=mean, username=request.user.username, is_running=True)
    notification_url = reverse('council:confirm_payment', args=(tx.id, signature))
    cancel_url = reverse('home')

    return_url = reverse('council:receipt', args=(payment.id, ))
    gateway_url = getattr(settings, 'IKWEN_PAYMENT_GATEWAY_URL', 'http://payment.ikwen.com/v1')
    endpoint = gateway_url + '/request_payment'
    user_id = request.user.username if request.user.is_authenticated() else '<Anonymous>'
    params = {
        'username': getattr(settings, 'IKWEN_PAYMENT_GATEWAY_USERNAME', service.project_name_slug),
        'amount': product.cost,
        'merchant_name': config.company_name,
        'notification_url': service.url + strip_base_alias(notification_url),
        'return_url': service.url + strip_base_alias(return_url),
        'cancel_url': service.url + strip_base_alias(cancel_url),
        'user_id': user_id
    }
    try:
        r = requests.get(endpoint, params)
        resp = r.json()
        token = resp.get('token')
        if token:
            next_url = gateway_url + '/checkoutnow/' + resp['token'] + '?mean=' + mean
            messages.success(request, 'You successfully paid your tax name' + product.name)
        else:
            logger.error("%s - Init payment flow failed with URL %s and message %s" % (service.project_name, r.url, resp['errors']))
            messages.error(request, resp['errors'])
            next_url = cancel_url
    except:
        logger.error("%s - Init payment flow failed with URL." % service.project_name, exc_info=True)
        next_url = cancel_url
    return HttpResponseRedirect(next_url)


def confirm_payment(request, *args, **kwargs):
    status = request.GET['status']
    message = request.GET['message']
    operator_tx_id = request.GET['operator_tx_id']
    phone = request.GET['phone']
    tx_id = kwargs['tx_id']
    try:
        tx = MoMoTransaction.objects.using(WALLETS_DB_ALIAS).get(pk=tx_id)
        if not getattr(settings, 'DEBUG', False):
            tx_timeout = getattr(settings, 'IKWEN_PAYMENT_GATEWAY_TIMEOUT', 15) * 60
            expiry = tx.created_on + timedelta(seconds=tx_timeout)
            if datetime.now() > expiry:
                return HttpResponse("Transaction %s timed out." % tx_id)
    except:
        raise Http404("Transaction %s not found" % tx_id)

    callback_signature = kwargs.get('signature')
    no_check_signature = request.GET.get('ncs')
    if getattr(settings, 'DEBUG', False):
        if not no_check_signature:
            if callback_signature != tx.task_id:
                return HttpResponse('Invalid transaction signature')
    else:
        if callback_signature != tx.task_id:
            return HttpResponse('Invalid transaction signature')

    if status != MoMoTransaction.SUCCESS:
        return HttpResponse("Notification for transaction %s received with status %s" % (tx_id, status))

    tx.status = status
    tx.message = message
    tx.processor_tx_id = operator_tx_id

council/templates/council/snippets/tax_list_results.html
{% load i18n static humanize %}
{% include 'core/snippets/spinner.html' %}
<div class="profile-list row">
    {% for obj in objects_page.object_list %}
        <div class="col-sm-4 col-lg-3" id="{{ obj.id }}" data-id="{{ obj.id }}">
            <div class="product {{ obj.status }} subtle-shade">
                <div>
                    <span class="image"
                       style="background-image: url({% get_media_prefix %}{{ obj.image.small_name }});"></span>
                </div>
                <div class="description">
                    <div>
                        <strong class="name">{{ obj.name }}</strong>
                        <div class="clearfix"></div>
                    </div>
                    <div class="key-points">
                        <div>
                            <strong>{% trans "Duration" %} :</strong>
                            <span>{{ obj.duration_text }}</span>
                        </div>
                        <div style="margin: 15px 0">
                            <sup style="font-size: 13px">{{ currency_symbol }}</sup>
                            <strong style="font-size: 25px">  {{ obj.cost|intcomma }}</strong>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                    <p class="about">
                        {{ obj.short_description }}
                    </p>
                    <button class="btn btn-block btn-outline-success {% if user.is_authenticated %}{% if created_profile %}payment-start{% else %}create-profile{% endif %}{% else %}prompt-login{% endif %}"
                            data-product-id="{{ obj.id }}" data-cost="{{ obj.cost }}">{% trans 'Pay' %}</button>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    {% endfor %}
</div>
{% include 'billing/snippets/modal_payment_options.html' %}
<script>
    (() => {
       $('.prompt-login').click(() => {
           let image = '{% static 'ikwen/img/login-to-proceed.jpg' %}',
               title = "{% trans "Login required" %}",
               message = "{% trans "Please, you need to login to proceed so that we know who is paying." %}",
               url = "{% url 'ikwen:sign_in' %}?next={% url 'home' %}";
           ikwen.showNoticeDialog(image, title, message, url);
       });
       $('.create-profile').click(() => {
           let image = '{% static 'ikwen/img/create-profile.jpg' %}',
               title = "{% trans "Profile required" %}",
               message = "{% trans "Please, you need to create your profile so that we know who is paying." %}",
               url = "{% url 'council:edit_profile' %}?next={% url 'home' %}";
           ikwen.showNoticeDialog(image, title, message, url);
       });
       {#$('.payment-start').click((e) => {#}
       {#    let amount = $(e.target).data('cost');#}
       {#   $('#amount').val(amount);#}
       {#});#}
    })()
</script>
{#{% if objects_page.paginator.num_pages > 1 %}#}
{#<ul class="pagination col-xs-12 col-sm-9">#}
{#    {% if objects_page.paginator.num_pages > max_visible_page_count and page_range.0 >= max_visible_page_count  %}#}
{#        <li class="page" data-val="first"><a href="javascript:;" aria-label="Previous"><span aria-hidden="true">«</span></a></li>#}
{#    {% endif %}#}
{#    {% for page in page_range %}#}
{#        <li class="page{% if page == objects_page.number %} active{% endif %}" data-val="{{ page }}">#}
{#            <a href="javascript:;">#}
{#                {{ page }} {% if page == objects_page.number %}<span class="sr-only">(current)</span>{% endif %}#}
{#            </a>#}
{#        </li>#}
{#    {% endfor %}#}
{#    {% if objects_page.paginator.num_pages > max_visible_page_count and max_page < objects_page.paginator.num_pages %}#}
{#        <li class="page{% if max_page == objects_page.paginator.num_pages %} disabled{% endif %}" data-val="-1"><a href="javascript:;" aria-label="Next"><span aria-hidden="true">»</span></a></li>#}
{#    {% endif %}#}
{#</ul>#}
{#{% endif %}#}
{#<div id="page-navigation" class="col-xs-12 col-sm-3" style="color: #3066b1">#}
{#    {% if objects_page.paginator.num_pages > 1 %}#}
{#        <p>{% blocktrans with count=objects_page.paginator.count start=objects_page.start_index end=objects_page.end_index %}#}
{#            {{ start }} – {{ end }} of {{ count }} results{% endblocktrans %}</p>#}
{#    {% else %}#}
{#        <p>{% blocktrans with count=objects_page.paginator.count %}{{ count }} results{% endblocktrans %}</p>#}
{#    {% endif %}#}
{#</div>#}