conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from ikwen_webnode.webnode.views import FlatPageView

from council.views import Home
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'conf.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^$', Home.as_view(), name='home'),
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^pinsview/', include('pinsview.urls', namespace='pinsview')),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),
    url(r'^', include('council.urls', namespace='council')),
    url(r'^$', Home.as_view(), name='home')
)

pinsview/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib import admin

from pinsview.views import save_optical_fiber_position, save_device_position, \
    delete_old_way, save_live_optical_fiber_coords, BaseView, filter_network_data, \
    find_lines, is_registered_member, search, get_techie_installation, get_selected_fiber, get_selected_device, \
    get_recent_equipments, Network, change_device_position, grab_fibers, grab_devices, save_device, grab_device_info, \
    update_fibers_distance, check_new_fiber, check_new_device, check_data_integrity, check_line_update, Statistic, \
    get_specific_fiber_data, get_specific_device_data, get_updated_fibers, load_equipments_by_city, grab_fiber_info, \
    get_asset_event_log, save_event_log, grab_event_log_detail, grab_offline_devices,update_device_cities,\
    save_asset_config, grab_asset_config, save_prospect, update_prospect_status

from admin_panel import *

SIGN_IN = 'login'
_extra_context = BaseView().get_context_data()

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', login_required()(Network.as_view()), name='network'),

    url(r'^changeCategory/$', ChangeDeviceCategory.as_view(), name='change_devicecategory'),
    url(r'^changeCategory/(?P<object_id>[-\w]+)$', ChangeDeviceCategory.as_view(), name='change_devicecategory'),
    url(r'^categoryList$', DeviceCategoryList.as_view(), name='devicecategory_list'),

    url(r'^changePin/$', ChangeDevice.as_view(), name='change_device'),
    url(r'^changePin/(?P<object_id>[-\w]+)$', ChangeDevice.as_view(), name='change_device'),
    url(r'^pinList$', DeviceList.as_view(), name='device_list'),

    url(r'^changeCity/$', ChangeCity.as_view(), name='change_city'),
    url(r'^changeCity/(?P<object_id>[-\w]+)$', ChangeCity.as_view(), name='change_city'),
    url(r'^cityList$', CityList.as_view(), name='city_list'),

    url(r'^findFiberlines', find_lines, name='find_lines'),
    url(r'^statistics$', user_passes_test(is_registered_member)(Statistic.as_view()), name='statistic'),
    url(r'^save_device$', save_device, name='save_device'),
    url(r'^save_device_position$', save_device_position, name='save_device_position'),
    url(r'^save_live_optical_fiber_coords$', save_live_optical_fiber_coords, name='save_live_optical_fiber_coords'),
    url(r'^filter_network_data$', filter_network_data, name='filter_network_data'),
    url(r'^delete_old_way$', delete_old_way, name='delete_old_way'),
    url(r'^save_fiber_way$', save_optical_fiber_position, name='save_fiber_way'),
    url(r'^full_search$', search, name='search'),
    url(r'^get_selected_device$', get_selected_device, name='get_selected_device'),
    url(r'^get_selected_fiber$', get_selected_fiber, name='get_selected_fiber'),
    url(r'^change_device_position$', change_device_position, name='change_device_position'),
    url(r'^get_techie_installation$', get_techie_installation, name='get_techie_installation'),
    url(r'^get_recent_equipments$', get_recent_equipments, name='get_recent_equipments'),
    url(r'^grab_fibers$', grab_fibers, name='grab_fibers'),
    url(r'^grab_devices$', grab_devices, name='grab_devices'),
    url(r'^grab_device_info$', grab_device_info, name='grab_device_info'),
    url(r'^grab_fiber_info$', grab_fiber_info, name='grab_fiber_info'),
    url(r'^update_fibers_distance$', update_fibers_distance, name='update_fibers_distance'),
    url(r'^check_new_fiber$', check_new_fiber, name='check_new_fiber'),
    url(r'^check_new_device$', check_new_device, name='check_new_device'),
    url(r'^check_device_data_integrity$', check_data_integrity, name='check_data_integrity'),
    url(r'^check_line_update$', check_line_update, name='check_line_update'),
    url(r'^get_specific_fiber_data$', get_specific_fiber_data, name='get_specific_fiber_data'),
    url(r'^get_specific_device_data$', get_specific_device_data, name='get_specific_device_data'),
    url(r'^get_updated_fibers$', get_updated_fibers, name='get_updated_fibers'),
    url(r'^load_equipments_by_city$', load_equipments_by_city, name='load_equipments_by_city'),

    url(r'^get_asset_event_log$', get_asset_event_log, name='get_asset_event_log'),
    url(r'^save_asset_config$', save_asset_config, name='save_asset_config'),
    url(r'^save_event_log$', save_event_log, name='save_event_log'),
    url(r'^grab_event_log_detail$', grab_event_log_detail, name='grab_event_log_detail'),
    url(r'^grab_asset_config$', grab_asset_config, name='grab_asset_config'),
    url(r'^grab_offline_devices$', grab_offline_devices, name='grab_offline_devices'),

    url(r'^update_device_cities$', update_device_cities, name='update_device_cities'),
    url(r'^save_prospect$', save_prospect, name='save_prospect'),
    url(r'^update_prospect$', update_prospect_status, name='update_prospect_status'),
)

pinsview/views.py
# Create your views here.
import json
import logging
import math

import random
import time
from datetime import datetime
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.utils.module_loading import import_by_path
from django.utils.translation import gettext as _
from django.views.decorators.cache import never_cache, cache_page
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.utils.decorators import method_decorator
from django.shortcuts import render, get_object_or_404
from django.utils.http import urlsafe_base64_decode, urlunquote, urlquote
from django.contrib.admin.models import LogEntry
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.contrib.contenttypes.models import ContentType
# import requests
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.hashers import check_password
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.views.generic.base import TemplateView

from ikwen.accesscontrol.models import Member

# from CreolinkLocalizer import settings
from conf import settings
from pinsview.models import Device, FiberEventData, DeviceCategory, Fiber, Zone, City, Operator, UserProfile, \
    LogEventType, AssetLog, Neighborhood, to_dict

logger = logging.getLogger('ikwen')
# from ajaxuploader.backends.local import LocalUploadBackend
# from ajaxuploader.views.base import AjaxFileUploader

_BOT = 'Bot'


def is_registered_member(user):
    return user.is_authenticated()


class BaseView(TemplateView):

    def get_context_data(self, **kwargs):
        context = super(BaseView, self).get_context_data(**kwargs)
        context['categories'] = DeviceCategory.objects.all()
        return context


class SignIn(TemplateView):
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            next_url = request.REQUEST.get('next')
            if next_url:
                return HttpResponseRedirect(next_url)
            else:
                next_url_view = getattr(settings, 'LOGIN_REDIRECT_URL', None)
                if next_url_view:
                    next_url = reverse(next_url_view)
                else:
                    next_url = reverse('pinsview:network')
            return HttpResponseRedirect(next_url)
        return super(SignIn, self).get(request, *args, **kwargs)

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            member = form.get_user()
            login(request, member)
            query_string = request.META.get('QUERY_STRING')
            next_url = request.REQUEST.get('next')
            if next_url:
                # Remove next_url from the original query_string
                next_url = next_url.split('?')[0]
                query_string = urlunquote(query_string).replace('next=%s' % next_url, '').strip('?').strip('&')
            else:
                next_url_view = getattr(settings, 'LOGIN_REDIRECT_URL', None)
                if next_url_view:
                    next_url = reverse(next_url_view)
                else:
                    next_url = reverse('pinsview:network')
            return HttpResponseRedirect(next_url + "?" + query_string)
        else:
            context = self.get_context_data(**kwargs)
            context['login_form'] = form
            if form.errors:
                error_message = getattr(settings, 'IKWEN_LOGIN_FAILED_ERROR_MSG',
                                        _("Invalid username/password or account inactive"))
                context['error_message'] = error_message
            return render(request, 'login.html', context)

FIBER_BLOCK_SIZE = 50
DEVICE_BLOCK_SIZE = 50


class Statistic(BaseView):
    template_name = 'pinsview/statistics.html'

    def get_context_data(self, **kwargs):
        context = super(Statistic, self).get_context_data(**kwargs)
        devices_qs = Device.objects
        fibers_qs = Fiber.objects
        device_categories = DeviceCategory.objects.all()
        #  ALL
        distance = 0
        for fiber in fibers_qs.all():
            distance += fiber.distance / 1000
        context['pending_fiber_count'] = fibers_qs.filter(status=Fiber.PENDING).count()
        context['validated_fiber_count'] = fibers_qs.filter(status=Fiber.VALIDATE).count()
        context['total_fiber_count'] = fibers_qs.all().count()
        context['total_devices_count'] = devices_qs.all().count()
        context['pending_total_devices_count'] = devices_qs.filter(status=Device.PENDING).count()
        context['validated_total_devices_count'] = devices_qs.filter(status=Device.VALIDATE).count()
        context['total_fiber_len'] = distance
        # DOUALA
        dla_distance = 0
        dla_devices_qs = devices_qs.filter(city__name='Douala')
        dla_fibers = fibers_qs.filter(city__name='Douala')
        for fiber in dla_fibers:
            dla_distance += fiber.distance / 1000
        context['dla_pending_fiber_count'] = dla_fibers.filter(status=Fiber.PENDING).count()
        context['dla_validated_fiber_count'] = dla_fibers.filter(status=Fiber.VALIDATE).count()
        context['dla_total_fiber_count'] = dla_fibers.count()
        context['dla_total_devices_count'] = dla_devices_qs.count()
        context['dla_pending_total_devices_count'] = dla_devices_qs.filter(status=Device.PENDING).count()
        context['dla_validated_total_devices_count'] = dla_devices_qs.filter(status=Device.VALIDATE).count()
        context['dla_total_fiber_len'] = dla_distance
        # yde
        yde_distance = 0
        yde_devices_qs = devices_qs.filter(city__name='Yaounde')
        yde_fibers = fibers_qs.filter(city__name='Yaounde')
        for fiber in dla_fibers:
            yde_distance += fiber.distance / 1000
        context['yde_pending_fiber_count'] = yde_fibers.filter(status=Fiber.PENDING).count()
        context['yde_validated_fiber_count'] = yde_fibers.filter(status=Fiber.VALIDATE).count()
        context['yde_total_fiber_count'] = yde_fibers.count()
        context['yde_total_devices_count'] = yde_devices_qs.count()
        context['yde_pending_total_devices_count'] = yde_devices_qs.filter(status=Device.PENDING).count()
        context['yde_validated_total_devices_count'] = yde_devices_qs.filter(status=Device.VALIDATE).count()
        context['yde_total_fiber_len'] = yde_distance
        fiber_groups = []
        device_groups = []
        yde_fiber_stat = []
        yde_device_stat = []
        fiber_stat = []
        device_stat = []
        dla_fiber_stat = []
        dla_device_stat = []

        dla_devices_qs = devices_qs.filter(city__name='Douala')
        dla_fibers = fibers_qs.filter(city__name='Douala')
        yde_devices_qs = devices_qs.filter(city__name='Yaounde')
        yde_fibers = fibers_qs.filter(city__name='Yaounde')

        for category in device_categories:
            devices_count = dla_devices_qs.filter(category=category).count()
            device_stats = {'category': category, 'devices_count': devices_count}
            dla_device_stat.append(device_stats)

        context['devices'] = device_groups
        context['fibers'] = fiber_groups

        context['fiber_stats'] = fiber_stat
        context['device_stats'] = device_stat

        context['yde_fiber_stats'] = yde_fiber_stat
        context['yde_device_stats'] = yde_device_stat

        context['dla_fiber_stats'] = dla_fiber_stat
        context['dla_device_stats'] = dla_device_stat

        return context


def update_device_city():
    devices_qs = Device.objects.all()
    city = City.objects
    for device in devices_qs:
        longitude = float(device.longitude)
        if 9 <= longitude <= 10:
            c = city.get(name='Douala')
        else:
            c = city.get(name='Yaounde')
        device.city = c
        device.save()


class Network(BaseView):
    # template_name = 'pinsview/equipments.html'
    template_name = 'pinsview/network.html'

    def get_context_data(self, **kwargs):

        context = super(Network, self).get_context_data(**kwargs)
        member = self.request.user
        try:
            profile = UserProfile.objects.get(member=member)
        except:
            profile = UserProfile.objects.create(member=self.request.user)
        user_cities = profile.city.all()
        default_city = City.objects.get(name='YAOUNDE')
        operator = profile.operator

        try:
            context['user_city'] = user_cities[0]
            user_city = user_cities[0]
        except:
            context['user_city'] = default_city
            user_city = default_city
        context['user_profile'] = profile
        context['event_types'] = LogEventType.objects.all()
        if member.is_superuser:
            count_fibers = Fiber.objects.filter(distance__gt=0).count()
        else:
            count_fibers = Fiber.objects.filter(operator=operator, city=user_city, distance__gt=0).count()
        fiber_blocks = int(math.ceil(float(count_fibers) / FIBER_BLOCK_SIZE))
        context['fiber_blocks'] = fiber_blocks

        # member = self.request.user
        profile = UserProfile.objects.get(member=member)
        operator = profile.operator
        all_fiber_count = Fiber.objects.all().count()
        all_device_count = Device.objects.all().count()

pinsview/templates/pinsview/snippets/edge_panel_left.html
{% load i18n humanize static cache %}
<div class="edge-panel-left-container">
    <div id="side-nav" class="edge-panel-left">
        <div class="wrapper">
            <div id="filter" class="">
                <div class="header top">
                    <h5 style="color: #696969; font-size: 20px">{{ service.project_name }}</h5>
                </div>
                <div class="filters" id="filtered">
                    {% if cities|length > 1 %}
                    <section class="cities">
                        <div class="header" style="margin-top: 0">Cities</div>
                        <div class="details">
                            <ul>
                                {% for city in cities %}
                                <li class="city">
                                    {% if request.user.is_superuser %}
                                        <a href="#" class="criterion" data-city="{{ city.id }}"  data-lat='{{ city.latitude }}' data-lng="{{ city.longitude }}">{{ city.name }}</a>
                                    {% else %}
                                        <a href="#" class="criterion" data-lat='{{ city.latitude }}' data-lng="{{ city.longitude }}">{{ city.name }}</a>
                                    {% endif %}
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </section>
                    {% endif %}
                    {% if show_operators %}
                    <section class="Fibers">
                        <div class="header">Operators</div>
                        <div class="details" style="margin-left: 5px">
                            {% for operator in operators %}
                                <label class="checkbox" style="padding-left: 0">
                                    <span class="color" style="background: {{ operator.fiber_color }}"></span><span class="op-name">{{ operator.name }}</span>
                                </label>
                            {% endfor %}
                        </div>
                    </section>
                    {% endif %}
                    <section class="Devices">
                        <div class="header">{% trans 'Categories' %}</div>
                        <div class="details">
                            {% for category in categories %}
                                <label class="checkbox">
                                    <input data-categoryid="{{ category.id }}" checked type="checkbox" class="criterion devicecategory" value="{{ category.id }}">{{ category.name }}
                                </label>
                            {% endfor %}
                        </div>
                    </section>
                    <section id="dist-reload"></section>
                </div>
            </div>
        </div>
    </div>
</div>

pinsview/templates/pinsview/snippets/edge_panel_right.html
 {% load i18n humanize static cache %}
<div id="asset-details" class="edge-panel-right always-docked">
    <div class="wrapper" style="padding: 0 10px">
        <div class="stage">
            <div class="top-edge-panel" style>
                <div class="panel-top" style="">
                    <div id="brand">
                        <div class="logo">
                            <span id="asset-name"></span>
                            <p class="text-muted" style="font-size: 14px; margin-top: 10px">{% trans "History" %}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="filters" id="filtered">
                <div>
                    <button class="btn add-event btn-success btn-sm" style="font-weight: 700; width: 100%">{% trans "Add event" %}</button>
                </div>
                <div class="event-list" style="margin-top: 25px;">
                    <ul class="asset-event-list">
                        <li class="event see-event-detail tpl">
                            <span class="type" style="font-weight: 600"></span>
                            <span class="created"></span>
                            <span class="title"></span>
                            <span class="summary"></span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

pinsview/templates/pinsview/snippets/toolbox.html
{% load i18n static %}

<div id="toolbox" class="hidden-xs">
    <div>
        <div class="coords subtle-shade hidden-sm">
            <div class="lat coord">
                <strong>Lat:</strong>
                <span id="latspan">0.0000</span>
            </div>
            <div class="lng coord" style="float: left;margin-left: 12px">
                <strong>Lng:</strong>
                <span id="lngspan">0.0000</span>
            </div>
        </div>
        <div class="action add-coords subtle-shade hidden-sm">
            <span id='add-coords' class="fa fa-plus" title="{% trans "Add new coordinates" %}"></span>
        </div>
{#        <div class="action live-drawing subtle-shade hidden-sm">#}
{#            <span id='live-drawing' class="fa fa-magic" title="{% trans "Live drawing" %}"></span>#}
{#        </div>#}
{##}
{#        <div class="action erase subtle-shade hidden-sm">#}
{#            <span id='erase' class="fa fa-eraser" title="{% trans "Clear the map" %}"></span>#}
{#        </div>#}
        <div class="action measure-line subtle-shade hidden-sm">
            <span id='measure-line' class="fa fa-arrows-h" title="{% trans "Measure" %}"></span>
        </div>
{#        <div class="action notifications subtle-shade hidden-sm">#}
{#            <span id='notifications' class="fa fa-bell" title="{% trans "View notifications" %}"><span class="badge"></span></span>#}
{#        </div>#}
        <div class="action view-all-equipments subtle-shade hidden-sm ik-hdn">
            <span id='view-all-equipments' class="fa fa-map-pin" title="{% trans "View all Equipment back" %}"></span>
        </div>
        <div class="action back-to-equipment subtle-shade hidden-sm ik-hdn">
            <span id='back-to-equipment' class="fa fa-street-view" title="{% trans "View all Equipment back" %}"></span>
        </div>
    </div>
    <div class="measure subtle-shade ik-hdn" id="current-polyline-length" style="background-color: #fff; color: #2cab2c; padding: 5px; position: fixed; right: 115px; top: 10px;z-index: 10">0.00 Meter</div>

    <div id="ld-tools-content" class="hidden-sm ik-hdn">
        <div id="ld-filter" class="subtle-shade">
{#            <div class="header">#}
{#                <h5>{% trans "Live drawing" %}</h5>#}
{#                <span class="glyphicon glyphicon-triangle-bottom"></span>#}
{#            </div>#}
{#            <section class="equipments" style="margin-top: 10px; ">#}
{#                <div class="details">#}
{#                    <ul>#}
{#                        <li id="back-to-equipment">#}
{#                             <a href="#" class="criterion">{% trans "View equipments" %}</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#            </section>#}
            <section id="line-search" class="hidden-xs" style="border-bottom: transparent; padding-bottom: 5px">
                <form role="form" id="line-search" style="clear: both; margin-left: 15px; margin-top: 5px">
                    <div class="form-group">
                         <label for="type" style="cursor: default; font-size: 12px">{% trans "Select a line" %}</label>
                         <input type="text" id="line-keyword" style="border-radius: 4px;font-size: 12px; width: 90%" placeholder="{% trans "Search a line" %}">
                         <input type="hidden">
                         <div id="suggestions-for-lines" style=""></div>
                    </div>
                    <div class="form-group ik-hdn">
                        <label for="type">Real Coords</label>
                        <textarea id="latlngBrutes" readonly="readonly"></textarea>
                    </div>
                    <div class="form-group ik-hdn">
                        <label for="type hidden">Encoded coords</label>
                        <textarea id="latlngEncodees" readonly="readonly"></textarea>
                    </div>
                    <div class="form-group" style="clear: both">
                         <button class="btn validate btn-success btn-sm" style="font-weight: 700; font-size: 12px; width: 169px;">{% trans "Submit" %}</button>
                    </div>
                </form>
            </section>
        </div>
        <div class="ld-toolbox" style="position: fixed; right:75px ; top:9px; z-index: 50">
            <div class="action subtle-shade" style="padding: 0">
                <button id='done' class="btn validate btn-success btn-sm" style="font-weight: 700; font-size: 12px;width: 90px;" title="Confirm">{% trans "Done" %}</button>
             </div>
        </div>
    </div>
    <div class="ld-toolbox" id="ld-toolbox" style="position: fixed; right:15px ; top:100px; z-index: 50">
        <div class="action subtle-shade" style="border-radius: 5px;height: 96px; width: 179px;padding: 0">
            <button id='update-done' class="btn validate btn-success btn-sm" style="font-weight: 700; font-size: 12px; margin: 12px;width: 150px;" title="Confirm">{% trans "Confirm line update" %}</button>
            <button id='cancel-update' class="btn validate btn-cancel btn-sm" style="font-weight: 700; font-size: 12px; margin-left: 12px;width: 150px;" title="Cancel">{% trans "Cancel update" %}</button>
         </div>
    </div>
</div>

pinsview/templates/pinsview/snippets/top-panel.html
{% load i18n static %}
<div id="top-panel" class="hidden-xs">
    <div id="search-box" class="subtle-shade">
        <div class="menu-button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </div>

        <div id="navbar-search" class="navbar-form navbar-left pinsview">
            <form id="search" autocomplete="off" onsubmit="return false">
                <i class="glyphicon glyphicon-menu-left hide-search visible-xs"></i>
                <i class="fa fa-search hidden-xs"></i>
                <input id="keyword" type="text" name="radix" class="form-control input-sm" placeholder="{% trans "Search" %}">
                <input type="hidden" name="q">
                <span class="spinner" style="display: block"></span>
            </form>
            <div id="navbar-results" class="item" data-min-search-chars="2">
                <div class="stage result" style="margin-left: -20px">
{#                    {% include 'core/snippets/spinner.html' %}#}
                    <div id="suggestions-for-view" style="display:none; margin-top: 20px">
                        <div class="close" style="padding: 5px 12px; margin-left: 350px;"> X </div>
                        <section class="techies">
                             <header>Techies</header>
                             <div class="result">
                                 <ul class="techie">
                                     <li class="ik-hdn choosen"><a href="#" data-type="techie" data-key="1"></a></li>
                                     <li class="line tpl"><a href="#" data-techname="" data-type="techie" data-key="1"></a></li>
                                 </ul>
                             </div>
                            <div class="more"></div>
                        </section>
                         <section class="fibers">
                             <header>Fibers</header>
                             <div class="more"></div>
                             <div class="result">
                                 <ul class="fiber">
                                     <li class="ik-hdn choosen"><a href="#" data-type="fiber" data-key=""></a></li>
                                     <li class="line tpl"><a href="#" data-type="techie" data-key="1"></a></li>
                                 </ul>
                            </div>
                             <div class="more"></div>
                         </section>
                         <section class="devices">
                             <header>Devices</header>
                             <div class="divider"></div>
                             <div class="result">
                                 <ul class="device">
                                     <li class="ik-hdn choosen"><a href="#" data-type="device" data-key=""></a></li>
                                     <li class="line tpl"><a href="#" data-type="" data-key="1"></a></li>
                                 </ul>
                             </div>
                             <div class="more"></div>
                         </section>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    {% include 'pinsview/snippets/toolbox.html' %}

</div>


<nav role="navigation" class="nav" style="top: -4px;">
    <ul class="nav-items">
        <li class="nav-item dropdown">
            <a href="#" class="nav-link" style="background: url('{% static "council/img/user-icon.png" %}');background-size: 100% auto; background-repeat: no-repeat;height: 31px;margin: 0 4px; padding: 5px 14px;"></a>
            <nav class="submenu">
                <ul class="submenu-items">
                    <li class="submenu-item" style="font-weight: 700; font-size: 12px; margin-left: 10px; overflow: hidden; width: 87%;">{{ request.user }}</li>
                    <li class="submenu-item"><hr class="submenu-seperator" /></li>
                    <li class="submenu-item"><a href="{% url 'ikwen:staff_router' %}" class="submenu-link" target="_blank">Admin</a></li>
                    {% if request.user.is_superuser %}
                    <li class="submenu-item"><a href="{% url 'pinsview:statistic' %}" class="submenu-link">Stats</a></li>
                    {% endif %}
                    <li class="submenu-item"><a href="{% url 'ikwen:logout' %}" class="submenu-link">Logout</a></li>
                </ul>
            </nav>
        </li>
    </ul>
</nav>