conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from ikwen_webnode.webnode.views import FlatPageView

from council.views import Home
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'conf.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^$', Home.as_view(), name='home'),
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^pinsview/', include('pinsview.urls', namespace='pinsview')),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),
    url(r'^', include('council.urls', namespace='council')),
    url(r'^$', Home.as_view(), name='home')
)

council/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required, permission_required

from council.views import Home, PaymentOrderList, Dashboard, ChangeTax, TaxList, Receipt, ChangePaymentOrder, \
    EditProfile, ProfileList, set_momo_payment, confirm_payment, PaymentList, Maps, \
    notify_outdated_payment_orders, ChangeProfile, ChangeBanner, BannerList, ProjectList, ChangeProject, CategoryList, ChangeCategory

urlpatterns = patterns(
    '',

    url(r'^kmth/dashboard/$', permission_required('council.ik_manage_dashboard')(Dashboard.as_view()),
                                                                                name='dashboard'),


    url(r'^kmth/payments/$', permission_required('council.ik_manage_payment')(PaymentList.as_view()), name='payment_list'),


    url(r'^kmth/categoryList/$', permission_required('council.ik_manage_category')(CategoryList.as_view()), name='category_list'),
    url(r'^kmth/changeCategory/$', permission_required('council.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),
    url(r'^kmth/changeCategory/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_category')(ChangeCategory.as_view()),
        name='change_category'),

    url(r'^kmth/taxList/$', permission_required('council.ik_manage_tax')(TaxList.as_view()), name='tax_list'),
    url(r'^kmth/changeTax/$', permission_required('council.ik_manage_tax')(ChangeTax.as_view()), name='change_tax'),
    url(r'^kmth/changeTax/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeTax.as_view()),
        name='change_tax'),


    url(r'^kmth/changeProfile/$', permission_required('council.ik_view_profile')(ChangeProfile.as_view()), name='change_profile'),
    url(r'^kmth/changeProfile/(?P<object_id>[-\w]+)/$',
        permission_required('council.ik_view_profile')(ChangeProfile.as_view()), name='change_profile'),
    url(r'^kmth/profileList/$', permission_required('council.ik_view_profile')(ProfileList.as_view()), name='profile_list'),


    url(r'^kmth/changeProject/$', permission_required('council.ik_view_project')(ChangeProject.as_view()),
        name='change_project'),
    url(r'^kmth/changeProject/(?P<object_id>[-\w]+)/$',
        permission_required('council.ik_view_profile')(ChangeProject.as_view()), name='change_project'),
    url(r'^kmth/projectList/$', permission_required('council.ik_view_project')(ProjectList.as_view()),
        name='project_list'),

    url(r'^kmth/paymentOrderList$',
        permission_required('council.ik_manage_payment_order')(PaymentOrderList.as_view()),
        name='paymentorder_list'),
    url(r'^kmth/changePaymentOrder/$',
        permission_required('council.ik_manage_payment_order')(ChangePaymentOrder.as_view()),
        name='change_paymentorder'),
    url(r'^kmth/changePaymentOrder/(?P<object_id>[-\w]+)$',
        permission_required('council.ik_manage_payment_order')(ChangePaymentOrder.as_view()), name='change_paymentorder'),


    url(r'^kmth/BannerList/$', permission_required('council.ik_manage_tax')(BannerList.as_view()), name='banner_list'),
    url(r'^kmth/changeBanner/$', permission_required('council.ik_manage_tax')(ChangeBanner.as_view()), name='change_banner'),
    url(r'^kmth/changeBanner/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeBanner.as_view()),
        name='change_banner'),


    # url(r'^home/$', Home.as_view(), name='home'),
    url(r'^profile/edit$', login_required(EditProfile.as_view()), name='edit_profile'),
    url(r'^maps$', login_required(Maps.as_view()), name='maps'),
    url(r'^receipt/(?P<receipt_id>[-\w]+)/$', login_required(Receipt.as_view()), name='receipt'),

    url(r'^set_momo_payment$', set_momo_payment),
    url(r'^confirm_payment/(?P<tx_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_payment, name='confirm_payment'),

    url(r'^notif$', notify_outdated_payment_orders, name='notify_outdated_payment_orders'),
)

pinsview/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib import admin

from pinsview.views import save_optical_fiber_position, save_device_position, \
    delete_old_way, save_live_optical_fiber_coords, BaseView, filter_network_data, \
    find_lines, is_registered_member, search, get_techie_installation, get_selected_fiber, get_selected_device, \
    get_recent_equipments, Network, change_device_position, grab_fibers, grab_devices, save_device, grab_device_info, \
    update_fibers_distance, check_new_fiber, check_new_device, check_data_integrity, check_line_update, Statistic, \
    get_specific_fiber_data, get_specific_device_data, get_updated_fibers, load_equipments_by_city, grab_fiber_info, \
    get_asset_event_log, save_event_log, grab_event_log_detail, grab_offline_devices,update_device_cities,\
    save_asset_config, grab_asset_config, save_prospect, update_prospect_status

from admin_panel import *

SIGN_IN = 'login'
_extra_context = BaseView().get_context_data()

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', login_required()(Network.as_view()), name='network'),

    url(r'^changeCategory/$', ChangeDeviceCategory.as_view(), name='change_devicecategory'),
    url(r'^changeCategory/(?P<object_id>[-\w]+)$', ChangeDeviceCategory.as_view(), name='change_devicecategory'),
    url(r'^categoryList$', DeviceCategoryList.as_view(), name='devicecategory_list'),

    url(r'^changePin/$', ChangeDevice.as_view(), name='change_device'),
    url(r'^changePin/(?P<object_id>[-\w]+)$', ChangeDevice.as_view(), name='change_device'),
    url(r'^pinList$', DeviceList.as_view(), name='device_list'),

    url(r'^changeCity/$', ChangeCity.as_view(), name='change_city'),
    url(r'^changeCity/(?P<object_id>[-\w]+)$', ChangeCity.as_view(), name='change_city'),
    url(r'^cityList$', CityList.as_view(), name='city_list'),

    url(r'^findFiberlines', find_lines, name='find_lines'),
    url(r'^statistics$', user_passes_test(is_registered_member)(Statistic.as_view()), name='statistic'),
    url(r'^save_device$', save_device, name='save_device'),
    url(r'^save_device_position$', save_device_position, name='save_device_position'),
    url(r'^save_live_optical_fiber_coords$', save_live_optical_fiber_coords, name='save_live_optical_fiber_coords'),
    url(r'^filter_network_data$', filter_network_data, name='filter_network_data'),
    url(r'^delete_old_way$', delete_old_way, name='delete_old_way'),
    url(r'^save_fiber_way$', save_optical_fiber_position, name='save_fiber_way'),
    url(r'^full_search$', search, name='search'),
    url(r'^get_selected_device$', get_selected_device, name='get_selected_device'),
    url(r'^get_selected_fiber$', get_selected_fiber, name='get_selected_fiber'),
    url(r'^change_device_position$', change_device_position, name='change_device_position'),
    url(r'^get_techie_installation$', get_techie_installation, name='get_techie_installation'),
    url(r'^get_recent_equipments$', get_recent_equipments, name='get_recent_equipments'),
    url(r'^grab_fibers$', grab_fibers, name='grab_fibers'),
    url(r'^grab_devices$', grab_devices, name='grab_devices'),
    url(r'^grab_device_info$', grab_device_info, name='grab_device_info'),
    url(r'^grab_fiber_info$', grab_fiber_info, name='grab_fiber_info'),
    url(r'^update_fibers_distance$', update_fibers_distance, name='update_fibers_distance'),
    url(r'^check_new_fiber$', check_new_fiber, name='check_new_fiber'),
    url(r'^check_new_device$', check_new_device, name='check_new_device'),
    url(r'^check_device_data_integrity$', check_data_integrity, name='check_data_integrity'),
    url(r'^check_line_update$', check_line_update, name='check_line_update'),
    url(r'^get_specific_fiber_data$', get_specific_fiber_data, name='get_specific_fiber_data'),
    url(r'^get_specific_device_data$', get_specific_device_data, name='get_specific_device_data'),
    url(r'^get_updated_fibers$', get_updated_fibers, name='get_updated_fibers'),
    url(r'^load_equipments_by_city$', load_equipments_by_city, name='load_equipments_by_city'),

    url(r'^get_asset_event_log$', get_asset_event_log, name='get_asset_event_log'),
    url(r'^save_asset_config$', save_asset_config, name='save_asset_config'),
    url(r'^save_event_log$', save_event_log, name='save_event_log'),
    url(r'^grab_event_log_detail$', grab_event_log_detail, name='grab_event_log_detail'),
    url(r'^grab_asset_config$', grab_asset_config, name='grab_asset_config'),
    url(r'^grab_offline_devices$', grab_offline_devices, name='grab_offline_devices'),

    url(r'^update_device_cities$', update_device_cities, name='update_device_cities'),
    url(r'^save_prospect$', save_prospect, name='save_prospect'),
    url(r'^update_prospect$', update_prospect_status, name='update_prospect_status'),
)

templates/website/snippets/edge_panel.html
{% load i18n humanize staticfiles cache auth_tokens %}
<div class="edge-panel-left-container visible-xs">
    <div id="side-nav" class="edge-panel-left subtle-shade" style="margin-left: -300px">
        <div class="wrapper">
            <div class="stage">
                <div class="top-edge-panel" style>
                    <div class="panel-top">
                    <img src="{% static 'council/img/council-logo.png' %}" class="img-responsive text-center" style="margin:auto; width: 60%">
                </div>
                <div class="divider"></div>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#taxes"><i class="fas fa-money-bill"></i><span style="margin-left: 3px">{% trans 'Pay your taxes' %}</span></a></li>
                        <li><a href="https://www.ikwen.com/foulassi/scolarfleet/deploy?is_baf_council=true"><i class="fas fa-school"></i><span style="margin-left: 3px">{% trans 'Digitalize your school' %}</span></a></li>
                        <li><a href="https://www.ikwen.com/tsunami/bundles?is_baf_council=true" target="_blank"><i class="fas fa-shopping-cart"></i><span style="margin-left: 3px">{% trans 'Create your online shop' %}</span></a></li>
                        <li><a href="{% url 'council:change_paymentorder' %}" target="_blank"><i class="fas fa-receipt"></i><span style="margin-left: 3px">{% trans 'Follow a payment order' %}</span></a></li>
                        {% if request.user.is_staff %}<li><a href="{% url 'pinsview:network' %}"><i class="fas fa-map-marker-alt"></i><span>{% trans 'Pinsview' %}</span></a></li>{% endif %}

                    </ul>
                    <div class="clearfix"></div>

                    <div class="social-icon">
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="https://www.youtube.com/watch?v=BZb0XFs73yc" target="_blank" class="ico-youtube" title="YouTube"><i class="fab fa-youtube-square"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="{{ config.instagram_link }}" target="_blank" class="ico-instagram" title="Instagram"><i class="fab fa-instagram"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="{{ config.twitter_link }}" target="_blank" class="ico-twitter" title="Twitter"><i class="fab fa-twitter-square"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="{{ config.facebook_link }}" target="_blank" class="ico-facebook" title="Facebook"><i class="fab fa-facebook-square"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" class="ico-whatsapp visible-xs" href="https://wa.me/{{ config.contact_phone }}"><i class="fab fa-whatsapp"></i></a>
                        {% include 'core/snippets/language_switcher.html' %}
                    </div>
                </div>
            </div>

            <div id="footer" class="text-muted">
                &copy; {{ year }} <a class="company-name" href="{{ service.url }}"><strong>{{ config.company_name }}</strong></a>.
                {% trans "All rights reserved." %}
                {% if config.legal_mentions_url %}
                - <a href="{{ config.legal_mentions_url }}" style="color: #666; text-decoration: none">{% trans "Legal mentions" %}</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>